<a href="https://colab.research.google.com/github/MohanaPriya-hub/Mohanapriya-TNSIF-C2TC_PythonProject/blob/main/Copy_of_MVIT_Batch_3____AI_%26_ML____NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy (Array Operations)

**NumPy** (Numerical Python) is a powerful library used for working with multi-dimensional arrays, performing fast mathematical operations, and manipulating large datasets efficiently.

### Characteristics:

* **ndarray:** The core data structure, representing an N-dimensional array.
* **Vectorized Operations:** Performs element-wise operations rapidly without slow explicit loops.
* **Homogeneous:** Stores elements of the same data type for high memory efficiency.

---

### Core Operations:

| Category | Function | Usage |
| :--- | :--- | :--- |
| **Creation** | `np.array()` | Create an array from a Python list |
| | `np.arange(start, stop, step)` | Create an array with a sequence/range of numbers |
| | `np.zeros((m,n))` / `np.ones((m,n))` | Create an array filled with 0s or 1s |
| | `np.eye(n)` | Create an $n \times n$ Identity Matrix |
| | `np.linspace(start, stop, num)` | Create evenly spaced numbers over a specified interval |
| | `np.random.rand(m,n)` | Generate random numbers between 0 and 1 |
| **Shape & Reshape** | `arr.shape` | Get dimensions/shape of an array |
| | `arr.reshape(rows, cols)` | Change array dimensions without altering data |
| | `np.transpose(arr)` | Transpose rows into columns (`arr.T`) |
| **Aggregations** | `np.sum()`, `np.mean()`, `np.std()` | Calculate total sum, average, and standard deviation |
| | `np.min()`, `np.max()` | Find smallest and largest values |
| | `np.argmin()`, `np.argmax()` | Find the index of smallest and largest values |
| **Linear Algebra & Utility** | `np.dot()`, `np.matmul()` | Perform matrix multiplication |
| | `np.sort()` | Return a sorted copy of an array |

---

1. Creating Arrays

In [ ]:
import numpy as np

# Create an array from a list
a = np.array([12, 23, 34])
print("Array:", a)

# Range of numbers (Start, Stop, Step)
b = np.arange(1, 7)
print("Range:", b)               # [1 2 3 4 5 6]

# Array of Zeros
c = np.zeros((2, 3))
print("Zeros:\n", c)

# Array of Ones
d = np.ones((2, 2))
print("Ones:\n", d)

# Identity Matrix
e = np.eye(3)
print("Identity Matrix:\n", e)

# Evenly spaced numbers (Start, Stop, Count)
f = np.linspace(10, 17, 3)
print("Linspace:", f)

# Random numbers between 0 and 1
g = np.random.rand(2, 4)
print("Random:\n", g)

Array: [12 23 34]
Range: [1 2 3 4 5 6]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Linspace: [10.  13.5 17. ]
Random:
 [[0.85832013 0.48068048 0.88012894 0.83759073]
 [0.15373935 0.52788313 0.70754497 0.22567829]]


2. Shape, Reshape & Transpose

In [ ]:
import numpy as np

arr = np.array([5,4,7,9,24,54])

# Get shape (dimensions)
print("Shape:", arr.shape)

# Reshape into 2 rows and 3 columns
matrix = arr.reshape(2, 3)
print("Reshaped (2x3):\n", matrix)

# Transpose (Swap rows and columns)
print("Transposed:\n", np.transpose(matrix))

Shape: (6,)
Reshaped (2x3):
 [[ 5  4  7]
 [ 9 24 54]]
Transposed:
 [[ 5  9]
 [ 4 24]
 [ 7 54]]


3. Math & Aggregations

In [ ]:
import numpy as np

nums = np.array([11, 41, 21, 55, 32])

# Basic stats
print("Sum:", np.sum(nums))
print("Mean:", np.mean(nums))
print("Std Dev:", np.std(nums))  # Standard deviation

# Min and Max values
print("Min Value:", np.min(nums)) # 11
print("Max Value:", np.max(nums)) # 55

# Index position of Min and Max
print("Min Index:", np.argmin(nums)) # 0 (index of 11)
print("Max Index:", np.argmax(nums)) # 3 (index of 55)

Sum: 160
Mean: 32.0
Std Dev: 15.31012736720371
Min Value: 11
Max Value: 55
Min Index: 0
Max Index: 3


4. Matrix Operations & Sorting

In [ ]:
import numpy as np

# Matrix Multiplication
A = np.array([[6, 7], [5, 8]])
B = np.array([[3, 1], [2, 4]])

result = np.matmul(A, B)
print("Matrix Multiplication:\n", result)

# Sorting an Array
unsorted = np.array([44, 11, 33, 22])
print("Sorted Array:", np.sort(unsorted))

Matrix Multiplication:
 [[32 34]
 [31 37]]
Sorted Array: [11 22 33 44]
