<a href="https://colab.research.google.com/github/MohanaPriya-hub/Mohanapriya-TNSIF-C2TC_PythonProject/blob/main/NumPy_Array_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy (Array Operations)

**NumPy** (Numerical Python) is a powerful library used for working with multi-dimensional arrays, performing fast mathematical operations, and manipulating large datasets efficiently.

### Characteristics:

* **ndarray:** The core data structure, representing an N-dimensional array.
* **Vectorized Operations:** Performs element-wise operations rapidly without slow explicit loops.
* **Homogeneous:** Stores elements of the same data type for high memory efficiency.

---

### Core Operations:

| Category | Function | Usage |
| :--- | :--- | :--- |
| **Creation** | `np.array()` | Create an array from a Python list |
| | `np.arange(start, stop, step)` | Create an array with a sequence/range of numbers |
| | `np.zeros((m,n))` / `np.ones((m,n))` | Create an array filled with 0s or 1s |
| | `np.eye(n)` | Create an $n \times n$ Identity Matrix |
| | `np.linspace(start, stop, num)` | Create evenly spaced numbers over a specified interval |
| | `np.random.rand(m,n)` | Generate random numbers between 0 and 1 |
| **Shape & Reshape** | `arr.shape` | Get dimensions/shape of an array |
| | `arr.reshape(rows, cols)` | Change array dimensions without altering data |
| | `np.transpose(arr)` | Transpose rows into columns (`arr.T`) |
| **Aggregations** | `np.sum()`, `np.mean()`, `np.std()` | Calculate total sum, average, and standard deviation |
| | `np.min()`, `np.max()` | Find smallest and largest values |
| | `np.argmin()`, `np.argmax()` | Find the index of smallest and largest values |
| **Linear Algebra & Utility** | `np.dot()`, `np.matmul()` | Perform matrix multiplication |
| | `np.sort()` | Return a sorted copy of an array |

---

1. Creating Arrays

In [1]:
import numpy as np

# Hours spent scrolling reels per day (Monday to Friday)
screen_time = np.array([4.5, 6.0, 5.2, 7.1, 8.5])
print("Screen Time (hrs):", screen_time)

# Days till weekend countdown (1 to 5)
days_to_friday = np.arange(1, 6)
print("Days countdown:", days_to_friday)

# Motivation level on Monday morning (All Zeros)
monday_motivation = np.zeros((2, 2))
print("Monday Motivation:\n", monday_motivation)

# Coffee cups consumed during exam week (All Ones)
coffee_cups = np.ones((2, 2))
print("Coffee Cups:\n", coffee_cups)

# Perfect sleep schedule (Identity Matrix: balanced diagonal)
sleep_matrix = np.eye(3)
print("Ideal Sleep Cycle Matrix:\n", sleep_matrix)

# 5 stages of panic before assignment deadline (0% to 100%)
panic_levels = np.linspace(0, 100, 5)
print("Panic Progression (%):", panic_levels)

# Random chances of waking up for the 8 AM lecture
wake_up_chance = np.random.rand(2, 2)
print("Wake Up Probability:\n", wake_up_chance)

Screen Time (hrs): [4.5 6.  5.2 7.1 8.5]
Days countdown: [1 2 3 4 5]
Monday Motivation:
 [[0. 0.]
 [0. 0.]]
Coffee Cups:
 [[1. 1.]
 [1. 1.]]
Ideal Sleep Cycle Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Panic Progression (%): [  0.  25.  50.  75. 100.]
Wake Up Probability:
 [[0.43105046 0.99590435]
 [0.25717358 0.17384694]]


2. Shape, Reshape & Transpose

In [3]:
import numpy as np

# 6 students in a single line
students = np.array(["Anu", "Balu", "Chitra", "Dev", "Ezhil", "Farhan"])

# Original dimensions
print("Line Shape:" , students.shape)

# Arrange into 2 rows of 3 benches
classroom = students.reshape(2, 3)
print("Classroom Grid (2x3):\n", classroom)

# Swap rows and columns (switch desk partners)
print("Rotated Seating:\n", np.transpose(classroom))

Line Shape: (6,)
Classroom Grid (2x3):
 [['Anu' 'Balu' 'Chitra']
 ['Dev' 'Ezhil' 'Farhan']]
Rotated Seating:
 [['Anu' 'Dev']
 ['Balu' 'Ezhil']
 ['Chitra' 'Farhan']]


3. Math & Aggregations

In [4]:
import numpy as np

# Snack expenses over 5 days (₹)
chai_bills = np.array([20, 55, 30, 80, 15])

# Total damage and averages
print("Total Chai Bill (₹):", np.sum(chai_bills))
print("Average Cost (₹):", np.mean(chai_bills))
print("Expense Volatility (Std Dev):", np.std(chai_bills))

# Best and worst spending days
print("Cheapest Snack (₹):", np.min(chai_bills))
print("Costliest Treat (₹):", np.max(chai_bills))

# Day index of lowest and highest spend
print("Cheapest Day Index:", np.argmin(chai_bills))
print("Splurge Day Index:", np.argmax(chai_bills))

Total Chai Bill (₹): 200
Average Cost (₹): 40.0
Expense Volatility (Std Dev): 24.289915602982237
Cheapest Snack (₹): 15
Costliest Treat (₹): 80
Cheapest Day Index: 4
Splurge Day Index: 3


4. Matrix Operations & Sorting

In [5]:
import numpy as np

# Matrix Multiplication: Module count x Dev hours per module
modules = np.array([[2, 1],
                    [3, 4]])

hours_rate = np.array([[5, 10],
                       [8, 12]])

workload = np.matmul(modules, hours_rate)
print("Sprint Workload Matrix:\n", workload)

# Sorting: Sort pending deadlines from urgent to chill (Days left)
deadlines = np.array([5, 1, 14, 2])
print("Sorted Deadlines (Days left):", np.sort(deadlines))

Sprint Workload Matrix:
 [[18 32]
 [47 78]]
Sorted Deadlines (Days left): [ 1  2  5 14]
